# بروتوكول الأمان: يتضمن SASL (للمصادقة) و SSL (للتشفير)
##edg@edg:/opt/kafka/config/kraft/client-sasl-ssl.properties
security.protocol=SASL_SSL


bootstrap.servers=192.168.168.25:9094


sasl.mechanism=SCRAM-SHA-512



sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="controller" password="controller-password";
#
ssl.keystore.location=/home/deepone/kafka_2.13-4.0.0/config/kraft/ssl/server/kafka.keystore.jks
ssl.keystore.password=kafkasslpass
ssl.key.password=kafkasslpass

# موقع ملف Truststore للعميل: يحتوي على شهادة المرجع المصدق (CA) الذي وقع شهادة الوسيط
ssl.truststore.location=/home/deepone/kafka_2.13-4.0.0/config/kraft/ssl/server/kafka.truststore.jks
ssl.truststore.password=kafkasslpass



