KafkaServer {
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username="controller"
    password="controller-password";
};
KafkaController {
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username="controller"
    password="controller-password";
};
